- hosts: all
  roles:
    - shout
  vars:
    secret_pw: "undefined"
  tasks:
    - name: "Operating System Used"
      debug:
        msg: "You are using {{ ansible_facts['distribution'] }}"

    - name: "Install Python 3 Pip"
      include_vars: "{{ ansible_facts['distribution'] }}.yml"
      delegate_to: 127.0.0.1
      connection: local
      become: yes
      package:
        - "{{ python3pip }}"

    - name: "Pip install dependencies"
      delegate_to: 127.0.0.1
      connection: local
      become: yes
      pip:
        name: fuzzywuzzy

    - name: "Run python script"
      script: actions.py
      register: outcome

    - debug:
        msg: "Outcome: {{ outcome.stdout }}"

    - debug:
        msg: "My secret is: {{ secret_pw }} "