- hosts: all
  vars:
    username: "not specified"
  tasks:
    - name: "Install Python 3 Pip"
      delegate_to: 127.0.0.1
      connection: local
      become: yes
      apk:
        name: py3-pip
        update_cache: yes
        state: present

    - name: "Pip install dependencies"
      delegate_to: 127.0.0.1
      connection: local
      become: yes
      pip:
        name: fuzzywuzzy

    - name: "Run python script"
      script: actions.py
      register: outcome

    - debug:
        msg: "Outcome: {{ outcome.stdout }}"

    - debug:
        msg: "My name is: {{ username }} "