- hosts: all
  roles:
    - shout
  vars:
    secret_pw: "undefined"
  tasks:
    - name: "Operating System Used"
      debug:
        msg: "You are using {{ ansible_facts['distribution'] }}"

    - include_vars: "{{ ansible_facts['distribution'] }}.yml"
    - include_vars: "Orange.yml"

    - name: "Install Python 3 Pip"
      delegate_to: 127.0.0.1
      connection: local
      become: yes
      package:
        name: "{{ item }}"
      with_items: "{{ dependencies }}"

    - name: "Pip install dependencies"
      delegate_to: 127.0.0.1
      connection: local
      become: yes
      pip:
        name:
          - fuzzywuzzy
          - boto
          - sqlalchemy
          # - google-cloud-storage
          # - psycopg2

    - name: "Run python script"
      script: actions.py
      register: outcome

    - debug:
        msg: "Outcome: {{ outcome.stdout }}"

    - debug:
        msg: "My secret is: {{ secret_pw }} "

    - debug:
        msg: "I love {{ animal }}"