name: Github Actions

on: push

jobs:
  work:
    name: Work It
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set env
        run: echo ::set-output name=test::$(echo $GITHUB_SHA | cut -c 1-6)
  
  cooldown:
    name: Cool Down
    needs: work
    runs-on: ubuntu-latest
    steps:

      - name: Test
        run: echo "There is some ${{ needs.job1.outputs.output1 }} I need"

      # - name: Run playbook
      #   uses: dawidd6/action-ansible-playbook@v2
      #   with:
      #     playbook: play.yml
      #     directory: ansible/playbooks
      #     options: |
      #       --extra-vars commit=$GITHUB_SHA_SHORT
      #       --inventory ../inventories
  