name: Github Actions

on: push

jobs:
  work:
    name: Work It
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set env
        id: step1
        run: echo ::set-output name=test::$(echo $GITHUB_SHA | cut -c 1-6)
  
  cooldown:
    name: Cool Down
    needs: work
    runs-on: ubuntu-latest

    steps:

      - name: Test
        run: echo "There is some ${{ needs.work.outputs.output1 }} I need"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Install python dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo -H pip install fuzzywuzzy

      - name: Run playbook
        uses: ./.github/actions/ansible
        with:
          workspace_dir: 'ansible'
          playbook: 'playbooks/play.yml'
          inventory_dir: 'inventories/hosts'


  